const express = require('express');
const cors = require('cors');
const crypto = require('crypto');

const app = express();
const PORT = process.env.PORT || 3001;

// Enable CORS for the marketing site
app.use(cors({
  origin: [
      'https://techpulse.dev', 
          'https://www.techpulse.dev', 
              'http://localhost:3000'
                ],
                  credentials: true
                  }));

                  app.use(express.json());

                  // In-memory storage for OTP codes (in production, use Redis)
                  const otpStore = new Map();
                  const userStore = new Map();

                  // Demo users
                  userStore.set('test@example.com', {
                    id: '1',
                      email: 'test@example.com',
                        name: 'Test User',
                          hasPaymentMethodOnFile: false
                          });

                          userStore.set('demo@techpulse.dev', {
                            id: '2',
                              email: 'demo@techpulse.dev',
                                name: 'Demo User',
                                  hasPaymentMethodOnFile: true
                                  });

                                  // Generate 6-digit OTP
                                  function generateOTP() {
                                    return Math.floor(100000 + Math.random() * 900000).toString();
                                    }

                                    // Generate JWT-like token
                                    function generateToken(user) {
                                      const payload = {
                                          userId: user.id,
                                              email: user.email,
                                                  exp: Date.now() + (24 * 60 * 60 * 1000) // 24 hours
                                                    };
                                                      return Buffer.from(JSON.stringify(payload)).toString('base64');
                                                      }

                                                      // Health check endpoint
                                                      app.get('/', (req, res) => {
                                                        res.redirect(`https://techpulse-remotepc-automation.onrender.com/app?token=${token}&email=${encodeURIComponent(user.email)}`);                                                                            res.status(500).json({ message: 'Google authentication failed' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Error handling middleware
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            app.use((err, req, res, next) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.error('🚨 Unhandled error:', err);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                res.status(500).json({ message: 'Internal server error' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // 404 handler
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                app.use('*', (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  res.status(404).json({ message: 'Endpoint not found' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // Start server
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  app.listen(PORT, () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.log(`🚀 TechPulse Authentication API running on port ${PORT}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.log(`📍 Health check: http://localhost:${PORT}/health`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        console.log(`📧 Send OTP: POST /api/auth/email/send-otp`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          console.log(`🔐 Verify OTP: POST /api/auth/email/verify-otp`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.log(`🔑 Google OAuth: POST /api/auth/google/callback`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            module.exports = app;
