const express = require('express');
const cors = require('cors');
const crypto = require('crypto');

const app = express();
const PORT = process.env.PORT || 3001;

// Enable CORS for the marketing site
app.use(cors({
  origin: [
      'https://techpulse.dev', 
          'https://www.techpulse.dev', 
              'http://localhost:3000'
                ],
                  credentials: true
                  }));

                  app.use(express.json());

                  // In-memory storage for OTP codes (in production, use Redis)
                  const otpStore = new Map();
                  const userStore = new Map();

                  // Demo users
                  userStore.set('test@example.com', {
                    id: '1',
                      email: 'test@example.com',
                        name: 'Test User',
                          hasPaymentMethodOnFile: false
                          });

                          userStore.set('demo@techpulse.dev', {
                            id: '2',
                              email: 'demo@techpulse.dev',
                                name: 'Demo User',
                                  hasPaymentMethodOnFile: true
                                  });

                                  // Generate 6-digit OTP
                                  function generateOTP() {
                                    return Math.floor(100000 + Math.random() * 900000).toString();
                                    }

                                    // Generate JWT-like token
                                    function generateToken(user) {
                                      const payload = {
                                          userId: user.id,
                                              email: user.email,
                                                  exp: Date.now() + (24 * 60 * 60 * 1000) // 24 hours
                                                    };
                                                      return Buffer.from(JSON.stringify(payload)).toString('base64');
                                                      }

                                                      // Health check endpoint
                                                      app.get('/', (req, res) => {
                                                        res.redirect(`https://techpulse-remotepc-automation.onrender.com/app?token=${token}&email=${encodeURIComponent(user.email)}`);
                                                                      });

                                                                      app.get('/health', (req, res) => {
                                                                        res.json({ 
                                                                            status: 'OK', 
                                                                                timestamp: new Date().toISOString() 
                                                                                  });
                                                                                  });

                                                                                  // Send OTP endpoint
                                                                                  app.post('/api/auth/email/send-otp', async (req, res) => {
                                                                                    try {
                                                                                        const { email } = req.body;

                                                                                                console.log(`ð§ OTP request for: ${email}`);
                                                                                                    
                                                                                                        if (!email) {
                                                                                                              return res.status(400).json({ message: 'Email is required' });
                                                                                                                  }
                                                                                                                      
                                                                                                                          // Generate OTP
                                                                                                                              const otp = generateOTP();
                                                                                                                                  
                                                                                                                                      // Store OTP with 5-minute expiration
                                                                                                                                          otpStore.set(email, {
                                                                                                                                                code: otp,
                                                                                                                                                      expires: Date.now() + (5 * 60 * 1000)
                                                                                                                                                          });
                                                                                                                                                              
                                                                                                                                                                  // Log OTP for demo purposes (remove in production)
                                                                                                                                                                      console.log(`ð OTP for ${email}: ${otp}`);
                                                                                                                                                                          
                                                                                                                                                                              res.json({ 
                                                                                                                                                                                    message: 'OTP sent successfully',
                                                                                                                                                                                          // Include OTP in response for demo purposes only
                                                                                                                                                                                                debug: { otp: otp }
                                                                                                                                                                                                    });
                                                                                                                                                                                                        
                                                                                                                                                                                                          } catch (error) {
                                                                                                                                                                                                              console.error('â Send OTP error:', error);
                                                                                                                                                                                                                  res.status(500).json({ message: 'Failed to send OTP' });
                                                                                                                                                                                                                    }
                                                                                                                                                                                                                    });
                                                                                                                                                                                                                    
                                                                                                                                                                                                                    // Verify OTP endpoint
                                                                                                                                                                                                                    app.post('/api/auth/email/verify-otp', async (req, res) => {
                                                                                                                                                                                                                      try {
                                                                                                                                                                                                                          const { email, otp } = req.body;
                                                                                                                                                                                                                              
                                                                                                                                                                                                                                  console.log(`ð OTP verification for: ${email} with code: ${otp}`);
                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                          if (!email || !otp) {
                                                                                                                                                                                                                                                return res.status(400).json({ message: 'Email and OTP are required' });
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                            // Check OTP
                                                                                                                                                                                                                                                                const storedOTP = otpStore.get(email);
                                                                                                                                                                                                                                                                    if (!storedOTP) {
                                                                                                                                                                                                                                                                          console.log(`â OTP not found for ${email}`);
                                                                                                                                                                                                                                                                                return res.status(400).json({ message: 'OTP not found or expired' });
                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                            if (Date.now() > storedOTP.expires) {
                                                                                                                                                                                                                                                                                                  otpStore.delete(email);
                                                                                                                                                                                                                                                                                                        console.log(`â° OTP expired for ${email}`);
                                                                                                                                                                                                                                                                                                              return res.status(400).json({ message: 'OTP expired' });
                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                          if (storedOTP.code !== otp) {
                                                                                                                                                                                                                                                                                                                                console.log(`â Invalid OTP for ${email}. Expected: ${storedOTP.code}, Got: ${otp}`);
                                                                                                                                                                                                                                                                                                                                      return res.status(400).json({ message: 'Invalid OTP' });
                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                  // Clear used OTP
                                                                                                                                                                                                                                                                                                                                                      otpStore.delete(email);
                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                              // Get or create user
                                                                                                                                                                                                                                                                                                                                                                  let user = userStore.get(email);
                                                                                                                                                                                                                                                                                                                                                                      if (!user) {
                                                                                                                                                                                                                                                                                                                                                                            user = {
                                                                                                                                                                                                                                                                                                                                                                                    id: crypto.randomUUID(),
                                                                                                                                                                                                                                                                                                                                                                                            email,
                                                                                                                                                                                                                                                                                                                                                                                                    name: email.split('@')[0],
                                                                                                                                                                                                                                                                                                                                                                                                            hasPaymentMethodOnFile: false
                                                                                                                                                                                                                                                                                                                                                                                                                  };
                                                                                                                                                                                                                                                                                                                                                                                                                        userStore.set(email, user);
                                                                                                                                                                                                                                                                                                                                                                                                                              console.log(`ð¤ Created new user: ${email}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                          // Generate token
                                                                                                                                                                                                                                                                                                                                                                                                                                              const token = generateToken(user);
                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.log(`â Authentication successful for: ${email}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                              res.json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    message: 'Authentication successful',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          user,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                token
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.error('â Verify OTP error:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  res.status(500).json({ message: 'Authentication failed' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Google OAuth callback endpoint
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    app.get('/api/auth/google/callback', async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const { code } = req.body;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  console.log(`ð Google OAuth callback with code: ${code?.substring(0, 10)}...`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // In production, exchange code for user info with Google
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // For demo purposes, create a mock Google user
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const mockGoogleUser = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        id: crypto.randomUUID(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              email: 'google.user@gmail.com',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    name: 'Google User',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          hasPaymentMethodOnFile: false
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const token = generateToken(mockGoogleUser);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.log(`â Google authentication successful`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      res.json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            message: 'Google authentication successful',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  user: mockGoogleUser,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        token
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.error('â Google auth error:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          res.status(500).json({ message: 'Google authentication failed' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Error handling middleware
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            app.use((err, req, res, next) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.error('ð¨ Unhandled error:', err);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                res.status(500).json({ message: 'Internal server error' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // 404 handler
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                app.use('*', (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  res.status(404).json({ message: 'Endpoint not found' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // Start server
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  app.listen(PORT, () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.log(`ð TechPulse Authentication API running on port ${PORT}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.log(`ð Health check: http://localhost:${PORT}/health`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        console.log(`ð§ Send OTP: POST /api/auth/email/send-otp`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          console.log(`ð Verify OTP: POST /api/auth/email/verify-otp`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.log(`ð Google OAuth: POST /api/auth/google/callback`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            module.exports = app;
